<?php

return [
    'languages' => [
        'actionscript' => 'ActionScript',
        'apache' => 'Apache',
        'applescript' => 'AppleScript',
        'bash' => 'Bash',
        'batch' => 'Batch',
        'c' => 'C',
        'cpp' => 'C++',
        'csharp' => 'C#',
        'css' => 'CSS',
        'go' => 'Go',
        'html' => 'HTML',
        'java' => 'Java',
        'javascript' => 'JavaScript',
        'json' => 'JSON',
        'less' => 'Less',
        'lua' => 'Lua',
        'markdown' => 'Markdown',
        'nginx' => 'Nginx',
        'php' => 'PHP',
        'python' => 'Python',
        'react' => 'React',
        'ruby' => 'Ruby',
        'rust' => 'Rust',
        'sass' => 'Sass',
        'scss' => 'SCSS',
        'sql' => 'SQL',
        'twig' => 'Twig',
        'typescript' => 'TypeScript',
        'yaml' => 'YAML',
    ],
];
